[package]
name = "grid-markup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"

[lib]
name = "grid_markup"
path = "src/lib.rs"

[[bin]]
name = "grid_parser"
path = "src/bin/parser.rs"
